
[tasks.ram-test]
# cargo run -- sample-ram/test.ram --input_file sample-ram/input_file
description = "RAMのプログラムをテストするタスク"
workspace = false
command = "cargo"
args = ["run", "--", "sample-ram/test.ram", "--input-file", "sample-ram/input_file" ]


[tasks.p1-1]
workspace = false
command = "cargo"
args = ["run", "--", "assignment/p1-1.ram", "--input-file", "assignment/p1-1.in", "--init-register", "assignment/p1-1.reg", ]

[tasks.debug-p1-1]
workspace = false
command = "cargo"
args = ["run", "--", "debug", "assignment/p1-1.ram", "--input-file", "assignment/p1-1.in", "--init-register", "assignment/p1-1.reg" ]

[tasks.p1-2]
workspace = false
command = "cargo"
args = ["run", "--", "assignment/p1-2.ram", "--init-register", "assignment/p1-2.reg", ]

[tasks.debug-p1-2]
workspace = false
command = "cargo"
args = ["run", "--", "debug", "assignment/p1-2.ram", "--init-register", "assignment/p1-2.reg" ]


[tasks.p2-1]
workspace = false
command = "cargo"
args = ["run", "-p", "p2", "--bin", "1"]

[tasks.p2-2]
workspace = false
command = "cargo"
args = ["run", "-p", "p2", "--bin", "2"]
